# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('blue_win_count', models.PositiveSmallIntegerField(verbose_name='Number of wins by the Blue team')),
                ('gold_win_count', models.PositiveSmallIntegerField(verbose_name='Number of wins by the Gold team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('trueskill_rating_mu', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TrueSkill.Rating mu parameter')),
                ('trueskill_rating_sigma', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TrueSkill.Rating sigma parameter')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Team')),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='hello.TeamMembership', to='hello.Player'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='blue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_result', to='hello.Team'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='gold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_result', to='hello.Team'),
        ),
    ]
