# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20171210_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('when', models.DateTimeField(verbose_name='event start time')),
            ],
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Event')),
            ],
        ),
        migrations.RenameField(
            model_name='gameresult',
            old_name='when',
            new_name='created',
        ),
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Team'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Event'),
        ),
        migrations.AddField(
            model_name='team',
            name='events',
            field=models.ManyToManyField(through='hello.EventTeam', to='hello.Event'),
        ),
    ]
