# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0003_auto_20171210_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='created',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
