# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_player_trueskill_rating_exposure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='trueskill_rating_exposure',
            field=models.FloatField(verbose_name='TrueSkill.Rating exposure.  Use this for sorting'),
        ),
        migrations.AlterField(
            model_name='player',
            name='trueskill_rating_mu',
            field=models.FloatField(verbose_name='TrueSkill.Rating mu parameter'),
        ),
        migrations.AlterField(
            model_name='player',
            name='trueskill_rating_sigma',
            field=models.FloatField(verbose_name='TrueSkill.Rating sigma parameter'),
        ),
    ]
