# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20171210_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Player')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(through='hello.EventPlayer', to='hello.Player'),
        ),
    ]
