# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20171213_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Determines whether this is a current event'),
        ),
    ]
