# Generated by Django 2.0 on 2017-12-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_event_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='style',
            field=models.PositiveSmallIntegerField(choices=[(2, 'DOUBLE_ELIMINATION_BRACKET'), (3, 'ROUND_ROBIN'), (1, 'SINGLE_ELIMINATION_BRACKET')], default=3, verbose_name='tournament style'),
        ),
    ]
