# Generated by Django 2.0 on 2017-12-16 20:45

from django.db import migrations
import hello.models.enums
import hello.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_event_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='style',
        ),
        migrations.AddField(
            model_name='event',
            name='tournament_style',
            field=hello.models.fields.EnumField(default=3, enum_class=hello.models.enums.TournamentStyle, verbose_name='tournament style'),
        ),
    ]
