# Generated by Django 2.0 on 2017-12-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20171216_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(through='hello.EventTeam', to='hello.Team'),
        ),
    ]
