# Generated by Django 2.0 on 2017-12-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Determines whether this is an active event'),
        ),
    ]
