# Generated by Django 2.0 on 2017-12-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20171220_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
    ]
