# Generated by Django 2.0 on 2017-12-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_auto_20171220_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=50, verbose_name='timezone'),
        ),
    ]
