# Generated by Django 2.0.1 on 2018-01-19 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_auto_20171231_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventplayer',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='eventplayer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='registration time'),
            preserve_default=False,
        ),
    ]
