# Generated by Django 2.0.1 on 2018-03-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_auto_20180327_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Season'),
        ),
    ]
