# Generated by Django 2.0.1 on 2018-03-27 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_auto_20180327_0212_squashed_0022_auto_20180327_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.Season'),
            preserve_default=False,
        ),
    ]
