# Generated by Django 2.0.1 on 2018-04-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0023_auto_20180401_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tournament_url',
            field=models.CharField(default='http://killer-queen-chattanooga.challonge.com/', max_length=255, verbose_name='tournament url'),
            preserve_default=False,
        ),
    ]
