# Generated by Django 2.0.1 on 2018-04-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_remove_event_tournament_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='map_losses',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of losses by map'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='map_wins',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of wins by map'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='match_losses',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of losses by match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='match_wins',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of wins by match'),
            preserve_default=False,
        ),
    ]
