# Generated by Django 2.0.1 on 2018-04-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_auto_20180409_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='map_losses',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of losses by map'),
        ),
        migrations.AlterField(
            model_name='player',
            name='map_wins',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of wins by map'),
        ),
        migrations.AlterField(
            model_name='player',
            name='match_losses',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of losses by match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='match_wins',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of wins by match'),
        ),
    ]
