# Generated by Django 2.0.1 on 2018-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0027_auto_20180409_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='token',
            field=models.CharField(default='', max_length=50, verbose_name='Secret token'),
        ),
    ]
