# Generated by Django 2.0.1 on 2018-05-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0029_player_wants_queen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='contributes_to_season_score',
            field=models.BooleanField(default=True),
        ),
    ]
