# Generated by Django 2.1 on 2018-08-28 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0030_gameresult_contributes_to_season_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='season start time'),
            preserve_default=False,
        ),
    ]
