# Generated by Django 2.1 on 2018-09-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0031_season_created_squashed_0032_season_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='win_order',
            field=models.CharField(default='', max_length=9, verbose_name='Win order'),
        ),
    ]
