# Generated by Django 2.1 on 2018-09-09 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0032_gameresult_win_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='blue_win_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of wins by the Blue team'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='gold_win_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of wins by the Gold team'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='win_order',
            field=models.CharField(default='', max_length=9, validators=[django.core.validators.RegexValidator('^[BGbg]*$', 'Only B or G characters are allowed.')], verbose_name='Win order'),
        ),
    ]
