# Generated by Django 2.1 on 2018-09-09 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0033_auto_20180909_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='win_order',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('^[BGbg]*$', 'Only B or G characters are allowed.')], verbose_name='Win order'),
        ),
    ]
