# Generated by Django 2.1.2 on 2019-01-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0034_auto_20180909_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='ghost_subs',
            field=models.BooleanField(default=True),
        ),
    ]
