# Generated by Django 2.1.5 on 2019-03-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0035_gameresult_ghost_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='blue_win_count',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='gold_win_count',
        ),
    ]
