# Generated by Django 2.1.5 on 2019-03-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0036_auto_20190313_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tournament_url',
        ),
    ]
