# Generated by Django 2.1.5 on 2019-03-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0037_remove_event_tournament_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('json', models.TextField(verbose_name='json')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='date last updated')),
            ],
        ),
    ]
