# Generated by Django 2.1.5 on 2019-03-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0040_auto_20190316_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinformation',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date last updated'),
        ),
    ]
