# Generated by Django 2.1.5 on 2019-04-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0042_event_cab_bracket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
    ]
