# Generated by Django 2.2.1 on 2019-07-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0043_remove_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_been_processed',
            field=models.BooleanField(default=False, verbose_name='Will disable reranking of players for this event'),
        ),
    ]
