# Generated by Django 2.2.1 on 2019-07-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0044_event_has_been_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='ghost_subs',
        ),
    ]
