# Generated by Django 2.2.1 on 2019-10-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0045_remove_gameresult_ghost_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_current',
        ),
    ]
